version: '3.9'

volumes:
    data_storage:

services:
    db:
        image: mysql:5.5
        container_name: mysql_training
        ports:
            - "3306:3306"
        environment:
            MYSQL_HOST: localhost
            MYSQL_USER: admin
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: training

        volumes:
            - data_storage:/var/lib/Mysql5.5-node

        networks:
            - default