version: '3.8'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=projet
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        ports:
            -   '48002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            -   './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '48000:80'
    php-fpm:
        build: php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            -   './php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

