version: "3.7"

services:
    app:
        image: node:12-alpine
        command: sh -c "yarn install && yarn run dev"
        ports:
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: '1234'
            MYSQL_DB: tests

    mysql:
        image: mysql:5.7
        volumes:
            - test-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '1234'
            MYSQL_DATABASE: test
volumes:
    test-mysql-data:


